### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by VD171**

### CODE REVIEW

**Comment by 0bbedCode** [comment]
Ok thank you ! Will merge

**Comment by 0bbedCode** [comment]
Can you Pull the Latest version then edit the PR , for the InetAddress I wish to keep though I can add another Hook for LinkProperties 

https://developer.android.com/reference/java/net/InetAddress#getHostName()

**Comment by VD171** [comment]
Done.
Had twice "name": "InetAddress.getHostName", just fixed to "name": "LinkProperties.getHostName".

**Comment by 0bbedCode** [comment]
thank you will merge !

**Pull request merged**
